/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0xCD, 0x03, 0x32, 0x5A, 0x33, 0xBE, 0x0F, 0x08}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 1 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }

#define POINTING_DEVICE_ROTATION_90
#define POINTING_DEVICE_INVERT_X
//#define POINTING_DEVICE_INVERT_Y

#define MASTER_RIGHT

#define ENCODER_A_PINS { }
#define ENCODER_B_PINS { }
#define ENCODER_RESOLUTIONS { }
#define ENCODER_A_PINS_RIGHT { GP29 }
#define ENCODER_B_PINS_RIGHT { GP28 }
#define ENCODER_RESOLUTIONS_RIGHT { 4 }

#define MASTER_RIGHT

#define POINTING_DEVICE_RIGHT
#define POINTING_DEVICE_CS_PIN GP2
#define POINTING_DEVICE_SCLK_PIN GP1
#define POINTING_DEVICE_SDIO_PIN GP0
// Not supported for split keyboard
// #define POINTING_DEVICE_MOTION_PIN GP8

#define POINTING_DEVICE_MOTION_PIN_ACTIVE_LOW

#define SPLIT_POINTING_ENABLE

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE

#define HOLD_ON_OTHER_KEY_PRESS
